name: dishoom
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  responsive_builder: ^0.2.0+2
  flutter_uploader: ^1.2.0
  flutter_ffmpeg: ^0.2.10
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.8.1
  camera: ^0.5.8+5
  video_player: ^0.10.11+2
  marquee: ^1.5.2
  carousel_slider: ^2.2.1
  flutter_staggered_grid_view: ^0.3.2
  flutter_icons: ^1.1.0
  path_provider: ^1.5.1
  path:
  fluttertoast:
  chewie: ^0.9.10
  image_picker: ^0.6.0+8
  file_picker: ^1.13.3
  dio: ^3.0.10
  video_trimmer: ^0.2.7
  country_code_picker: ^1.4.0
  rxdart: ^0.24.1
  shared_preferences: ^0.5.10
  http: ^0.12.2
  geolocator: ^5.3.1
  flutter_bloc: ^6.0.5
  permission_handler: ^4.4.0+hotfix.2
  cached_network_image: ^2.3.1
  audioplayers: ^0.16.1
  modal_progress_hud: ^0.1.3
  flutter_speed_dial: ^1.2.5
  flutter_launcher_icons: ^0.7.5
  fab_circular_menu: ^1.0.0

  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_messaging: ^6.0.15
  firebase_core: ^0.4.4+3
  firebase_database: ^3.1.5

  video_thumbnail: ^0.2.2
  android_intent: ^0.3.7+2
  unicorndial: ^1.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_logo_launcher.jpeg"
  image_path_android: "assets/launcher/ic_logo_launcher.jpeg"

flutter:

  uses-material-design: true

  assets:
    - assets/images/